import React from 'react';
import Image from 'next/image';
import { BsFillFileEarmarkPdfFill } from 'react-icons/bs';
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'About | Nicolas Moina',
    description: 'Generated by create next app',
}

function AboutMe() {
    return (
        <div>
            <h1 className="text-4xl font-bold my-8 sm:my-16 text-center sm:text-left">Sobre mi</h1>
            <div className="flex flex-col sm:flex-col sm:space-x-0 md:flex-col lg:flex-row justify-between items-center space-y-8 sm:space-y-0 md:space-x-16 my-12">
                <p className='w-[110%]'>
                    ¡Hola! Soy Nicolas Moina, un ingeniero en ciencias de la computación apasionado por el desarrollo web, el análisis de datos y la ciberseguridad. He tenido la oportunidad de trabajar en diversas capacidades, incluyendo como analista de datos en Diners Club International, desarrollador full stack en la Universidad San Francisco de Quito y analista de ciberseguridad en Banco Pichincha.<br></br> <br/>
                    
                    A lo largo de mi carrera, he implementado varias automatizaciones de tareas, trabajado con bases de datos, desarrollado sitios web y evaluado vulnerabilidades en infraestructuras tecnológicas. Además, he mejorado la eficiencia de las solicitudes HTTP y añadido seguridad extra a las API. <br /> <br />
                    Soy un orgulloso estudiante de la Universidad San Francisco de Quito, donde obtuve una beca de ciencias de la computación y formé parte de la lista del decano. También soy miembro del club de programación competitiva. <br /> <br />
                    Estoy competente en una variedad de lenguajes y tecnologías, incluyendo Python, JavaScript, Node.js, React, NextJS, C++, Java, Flutter, GatsbyJS, SQL, MySQL, MongoDB, Git, GitHub, Jira y Scrum. Tengo un gran interés en el desarrollo web, la ciencia de datos, la inteligencia artificial, el desarrollo móvil y el desarrollo de backend. <br /> <br />
                    Además de mi experiencia laboral y educativa, he completado una serie de cursos en línea para mejorar aún más mis habilidades. Soy comunicativo, trabajo bien en equipo, resuelvo problemas y me motivo a mí mismo. Hablo español e inglés con fluidez. <br /> <br />
                    Puedes encontrar más sobre mí en mi perfil de <a href='www.linkedin.com/in/nicolas-moina-21a85b20a'>Linkedin</a> y en mi perfil de <a href='www.github.com/elrichi31'>Github</a>. También puedes ver todos los cursos que he completado en mi perfil de <a href="www.platzi.com/p/nmoina/">Platzi</a>.
                </p>
                <div className="md:w-[100rem] py-14">
                    <Image src="/aboutme.png" width={1000} height={1000} alt="aboutme"></Image>
                </div>
            </div>
            <div className='flex justify-center items-center'>
                <button>
                    <a href="/CV_Nicolas_Moina.pdf" className="bg-[#008734] text-white rounded-xl px-4 py-2 flex items-center gap-2 hover:bg-[#01732D]">
                        Descarga mi CV
                        <BsFillFileEarmarkPdfFill />
                    </a>
                </button>
            </div>
        </div>

    );
}

export default AboutMe;
